name: Deploy EKS Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v2

    # Configurar as credenciais AWS com secrets para acesso ao EKS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Instalar o Terraform para gerenciar a infraestrutura no EKS
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    # Inicializar o Terraform para criar/atualizar o cluster EKS
    - name: Terraform Init
      run: terraform init
      working-directory: ./kubernetes-infra/terraform

    # Aplicar o Terraform para provisionar o cluster EKS
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./kubernetes-infra/terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Instalar o kubectl para interagir com o EKS
    - name: Setup kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.22.0'  # Ajuste de acordo com a versão necessária para o seu cluster EKS

    # Obter o contexto do cluster EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name <nome-do-cluster-EKS>